backend:
  name: git-gateway
  branch: master # Nhánh git của bạn

local_backend: true # Cho phép test CMS dưới local không cần push git

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Quản lý Cấu hình Trang"
    files:
      - label: "Trang Chủ (Timeline, v.v...)"
        name: "home"
        file: "content/pages/home.md"
        fields:
          - label: "Quản lý Timeline"
            name: "timeline"
            widget: "list"
            fields:
              - { label: "Thời gian (VD: 2021-now)", name: "dates", widget: "string" }
              - { label: "Nội dung", name: "content", widget: "markdown", buttons: ["bold", "italic", "link"] }
